In [54]:
import numpy as np

In [55]:
arr1=np.array([1,2,3,4,5,6,7])
arr1

array([1, 2, 3, 4, 5, 6, 7])

In [56]:
arr1.ndim

1

In [57]:
arr2=np.array([[1,2,3],[11,12,13]])
arr2

array([[ 1,  2,  3],
       [11, 12, 13]])

In [58]:
#Shape of array(No of rows & Column)
arr2.shape

(2, 3)

In [59]:
#creating array starting from 1 to 16
arr3=np.arange(1,17)
arr3

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

In [60]:
#displaying datatype of array
arraydt=np.array([1.0,2.0,3.0,4.0,])
arraydt.dtype

dtype('float64')

In [61]:
#Reshaping array into 4X4 matrix
X=arr3.reshape(4,4)
print(X)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [62]:
#addition of Arrays aar3 and arr4
arr4=np.array([[2,4,6],[3,5,7],[8,9,10]])
arr5=np.array([[12,13,14],[15,16,17],[18,19,20]])
print(arr4)
print(arr5)
print("---------------")
addition= arr4 +arr5
addition

[[ 2  4  6]
 [ 3  5  7]
 [ 8  9 10]]
[[12 13 14]
 [15 16 17]
 [18 19 20]]
---------------


array([[14, 17, 20],
       [18, 21, 24],
       [26, 28, 30]])

In [63]:
#substraction of arrays arr4 & arr5
substration=arr4 - arr5
substration

array([[-10,  -9,  -8],
       [-12, -11, -10],
       [-10, -10, -10]])

In [64]:
#division of arrays arr4 and arr5
division=arr4/arr5
division

array([[0.16666667, 0.30769231, 0.42857143],
       [0.2       , 0.3125    , 0.41176471],
       [0.44444444, 0.47368421, 0.5       ]])

In [65]:
#Multiplication of arrays Arr4 and arr5
Multiplication=arr4*arr5
Multiplication

array([[ 24,  52,  84],
       [ 45,  80, 119],
       [144, 171, 200]])

In [66]:
Square=arr4**arr5
Square

array([[               4096,            67108864,         78364164096],
       [           14348907,        152587890625,     232630513987207],
       [  18014398509481984, 1350851717672992089, 7766279631452241920]])

In [67]:
#displaying Maximum and Minimum Values of arrays
print("Minimun value of array arr4 is:", np.min(arr4))
print("Maximun value of array arr4 is:", np.max(arr5))


Minimun value of array arr4 is: 2
Maximun value of array arr4 is: 20


In [68]:
#creating middle spaces of the array
SP=np.linspace(1,10,num=5)
SP

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [ ]:
#Displaying index value of the array
y=np.array([9,8,7,6,5,4,3,2,1])
y[8]

np.int64(1)

In [79]:
#docstring of array
?y

Type:        ndarray
String form: [9 8 7 6 5 4 3 2 1]
Length:      9
File:        c:\users\hp\appdata\roaming\python\python313\site-packages\numpy\__init__.py
Docstring:  
ndarray(shape, dtype=float, buffer=None, offset=0,
        strides=None, order=None)

An array object represents a multidimensional, homogeneous array
of fixed-size items.  An associated data-type object describes the
format of each element in the array (its byte-order, how many bytes it
occupies in memory, whether it is an integer, a floating point number,
or something else, etc.)

Arrays should be constructed using `array`, `zeros` or `empty` (refer
to the See Also section below).  The parameters given here refer to
a low-level method (`ndarray(...)`) for instantiating an array.

For more information, refer to the `numpy` module and examine the
methods and attributes of an array.

Parameters
----------
(for the __new__ method; see Notes below)

shape : tuple of ints
    Shape of created array.
dtype : data-type, op

In [84]:
#displaying maximum and minimum index values of array
print(arr4)
print(np.argmax(arr4))
print(np.argmin(arr4))

[[ 2  4  6]
 [ 3  5  7]
 [ 8  9 10]]
8
0
